### PR TITLE
Add 2.4.0 for travis (allowing failure).

### PR DESCRIPTION
**Pull request by gkellogg**
Change references for Fixnum to Integer.
Updates to RDF::Literal::Decimal for differences in BigDecimal.

### CODE REVIEW

**Comment by no-reply** [comment]
Looks good. The difference on the RDF::URI test seems to be that `String` now properly handles unicode cases. Various of the URI fragments are downcased during canonicalization. As near as I can tell from a quick skim of RFC 3986, the new behavior is correct.

**Comment by no-reply** [comment]
In case we determine that the new unicode case behavior is incorrect, we have the option of using `String#downcase(:ascii)` to revert to the older behavior.

**Comment by gkellogg** [comment]
I wasn't trying to address the conversion issues, but simply limit the described behavior. But, perhaps the URI canonicalization can be improved. It's currently implemented in `normalize_segment` using `::URI.encode(decoded, /[^(?:#{expr})]/)`. We could special-case `normalized_scheme` to work as you say, but right now we're just sticking to the implementation describe in the RFC. In reality, I don't expect to encounter any issues here.

**Comment by no-reply** [comment]
> In reality, I don't expect to encounter any issues here.

Agreed.

Looking a little closer at the URI/IRI specs, I do think this will be closer to on-spec behavior. IRI calls for use of NAMEPREP/STRINGPREP mappings, which include case mappings. There are probably a bunch of edge cases, but I think this will fix some canonical URI comparisons that were previously broken.

**Comment by gkellogg** [comment]
Great, would you like to take this on?

**Comment by no-reply** [comment]
> Great, would you like to take this on?

I think it's already done. :)

**Comment by gkellogg** [comment]
Okay, I thought you were discussing using `String#downcase(:ascii)`, but it must be the change to Ruby 2.4 you were discussing.

**Comment by no-reply** [comment]
Yes. To be clear, I think the new unicode case mappings are an improvement.

**Pull request merged**
