### PR TITLE
* Fix validate! in Value to return self, as is documented.

### PR DESCRIPTION
**Pull request by gkellogg**
* Add Pattern#valid? to improve on Statement#valid? for legitimate patterns.
* Improve Query#validate! to validate patterns, not require the first pattern to not be optional, and modernize check for appropriate partition of required and optional patterns.

### CODE REVIEW

**Comment by gkellogg** [comment]
@bendiken & @no-reply if you could verify some assumptions on query validation. Previously, a query had to have at least one pattern, but this was updated for SPARQL to add a pattern, if none exists, as (bgp) is a legitimate SPARQL Algebra pattern, and the following is legitimate:

    (left_join (bgp) (bgp (triple :a :b :c))

Which would create a Query where the first pattern is optional, and the first query has no patterns.

**Comment by no-reply** [comment]
@gkellogg that looks right to me, and this looks good to go.

Do we want to get some tests in for this?

**Comment by gkellogg** [comment]
Working on the tests right now. Thanks.

**Comment by bendiken** [comment]
LGTM.

Off-topic, note that we probably ought to tighten up the context type requirement a bit--never yet actually seen a store that permits blank nodes as graph identifiers, they're always URIs. (Blank nodes cause enough headache as it is ;)) That would affect `RDF::Query::Pattern#valid?` here.

**Comment by no-reply** [comment]
@bendiken I think the URI constraint is correct for [SPARQL](http://www.w3.org/TR/2013/REC-sparql11-query-20130321/#rdfDataset), but [CONCEPTS](http://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/#dfn-graph-name) explictly allows bnode graph names.

There might be some non-horrifying use cases for bnode "named" graphs; particularly where you don't know or don't care where a graph came from, but need to query it independently over the short term.  I'd be inclined to handle bnodes in `RDF::Query::Pattern` without complaint.

**Comment by gkellogg** [comment]
The RDF data model allows for graph names to be BNodes, a
Though it was a contentious issue. JSON-LD allows BNodes as well, but TriG does not support it. N3 also allows literal subjects and BNode properties; I believe N3 monkey patches Statement to allow this.

**Comment by bendiken** [comment]
@no-reply Had forgotten about that. So, yes, let's keep that as it is. Though anybody who uses the feature has only themselves to blame... it won't roundtrip with anything, modulo Gregg's comment.

@gkellogg Good point about JSON-LD.

**Comment by no-reply** [comment]
:rocket:

**Pull request merged**
