### PR TITLE
add RDF::Vocabulary.register and make appropriate changes

### PR DESCRIPTION
**Pull request by doriantaylor**
This is a provisional `RDF::Vocabulary.register` method and attendant accoutrements. [`rdf/vocab/extensions.rb`](/ruby-rdf/rdf-vocab/blob/develop/lib/rdf/vocab/extensions.rb) will have to be changed as well. I have held off on adding the call to register to the generated vocabularies for now, but one could easily put `RDF::Vocabulary.register :prefix, self` at the bottom of `rdf/vocab/writer.rb`.

(I'm not sure what's up with all those other commits but they don't seem to net out to any changes. Note as well that method in `RDF::Changeset` tagged along from something else; it's harmless.)

### CODE REVIEW

**Comment by doriantaylor** [comment]
okay that is weird: those URI schemes that failed in my tests which I changed are now failing in CI. what gives?

**Comment by gkellogg** [comment]
The failures seem to be because it's looking for `http://rubygems.org/gems/rdf` and not `https://rubygems.org/gems/rdf`. Is it possible your fork isn't up to date with develop?

**Comment by doriantaylor** [comment]
Yeah I had it like that initially (ie untouched) but if I change it back to `https` it fails the tests locally.

**Comment by gkellogg** [comment]
Some dependency must not be right. I’ll clone your branch and try locally later.

**Comment by gkellogg** [comment]
Changing them back allow tests to succeed for me; if you're using an old version of the rdf-spec gem, that might use the non-https versions, but if you do a `bundle update` that should clear things out.

Not sure why you're getting merge conflicts, though, if you've rebased to develop.

**Comment by doriantaylor** [comment]
Don't forget https://github.com/ruby-rdf/rdf-vocab/pull/66!

**Comment by gkellogg** [comment]
> Don't forget [ruby-rdf/rdf-vocab#66](https://github.com/ruby-rdf/rdf-vocab/pull/66)!

Yup, already merged.

**Comment by gkellogg** [comment]
Are you ready for a release including that, or want to work with it some more?

**Comment by doriantaylor** [comment]
nope it's good to go

**Pull request merged**
