### PR TITLE
Feature/mutable del ins

### PR DESCRIPTION
**Pull request by no-reply**
Tested in https://github.com/ruby-rdf/rdf-spec/pull/38

### CODE REVIEW

**Comment by no-reply** [comment]
The test failures predate these changes. Do we know what the cause is, or should I go digging?

**Comment by gkellogg** [comment]
Yeah, there are a couple of thing broken after the 2.0 merge I'm working on. I'll clear these all out today

**Comment by gkellogg** [comment]
Don't have time to look into details right now, but delete_insert specs are broken on rdf-do, rdf-mongo, and sparql-client Repository.

**Comment by no-reply** [comment]
It looks to me like `sparql-client` doesn't handle the `:each_statement` case.  See:

  - https://github.com/ruby-rdf/sparql-client/blob/develop/lib/sparql/client/repository.rb#L189-L201
  - https://github.com/ruby-rdf/sparql-client/blob/develop/lib/sparql/client/repository.rb#L258-L280

I added a test that passes on the base `Mutable` but that repository fails. I suspect we have the same problem in `rdf-do` and `rdf-mongo`, but won't likely be able to check in on them until next week.

https://github.com/ruby-rdf/rdf-spec/pull/39

**Pull request merged**
