### PR TITLE
Feature/issue 333 to h

### PR DESCRIPTION
**Pull request by gkellogg**

### CODE REVIEW

**Comment by no-reply** [comment]
:+1:

Do we want to consider removing various instances of `#to_str`, `#to_ary`, and company?

**Comment by no-reply** [comment]
Also, I'm thinking it might be better to replace the `#method_missing` call with:

```ruby
def to_hash(*args)
   warn "..."
   to_h(*args)
end
```

**Comment by gkellogg** [comment]
The problem is, if we implement #to_hash, it automatically enables the implicit conversion, which is the root of the problem.

**Comment by no-reply** [comment]
Ah, I see, we want `respond_to?(:to_hash)` to be `false`. I see the tests check that, now.

In that case, the same approach will probably work for `Enumerator/Statement#to_ary`.

**Comment by no-reply** [comment]
:+1: on looking at places where `#to_a` and `#to_s` are called for.

`#to_str` isn't implemented on literals now, so introducing it for stringy datatypes should be safe.

I have WIP on the changes to implicit conversion I have in mind, and will submit a PR tomorrow. It might be a bit limited, since I don't think `#respond_to?` is called in `Array()`; but we can clean this up as much as possible without breaking changes and take it from there.

**Pull request merged**
