### PR TITLE
Performance fixes

### PR DESCRIPTION
**Pull request by jperville**
This PR contains several small performance fixes for json-ld. After merging all these fixes, a sample scenario that loads a moderate-sized json-ld file then does a lot of manipulations on it using Spira will be roughly 30% faster.

It consists in:
 - improvements suggested by the 'fasterer' gem (the major one was to use yield instead of `block.call` when possible; other improvements were the use of `Enumerable#flat_map` and the use of block form of `Hash#fetch` instead of using 2 argument form)
 - removal of useless code in the extensively-used `RDF::URI#initialize` method
 - use `Hash.[]` instead of `Hash#dup` when parsing options (the difference is that Hash[] does not dup the string keys of the hash, reducing the number of allocations)
 - refactor of the `RDF::Statement` class to use if/elsif instead of a big case when testing the different subclass cases when possible (this + reordering the clauses to avoid unneeded `Kernel.is_a?` calls made a significant difference)

To test performance, I ran the scenario for 30s with `Benchmark.ips`. The higher the numbers below the better.

Results before changes:
```
CreateMedia.bm_create_media
                          6.791  (±29.5%) i/s -    181.000 
```

Results after optimisations:
```
CreateMedia.bm_create_media
                          8.597  (±11.6%) i/s -    250.000 
```

There is still a lot of room for improvements, the pprof.rb graph shows that a good 20% of the execution time is spent in garbage collector.

### CODE REVIEW

**Comment by jperville** [comment]
This PR is the companion of ruby-rdf/json-ld#19.

**Comment by gkellogg** [comment]
Thanks, i've merged this into the develop branch. Note that all PRs should go to develop.

These techniques can be broadly useful across the various RDF gems.

**Comment by gkellogg** [comment]
We may need to back out (some or all of) the `yield` vs `block.call()` changes due to an MRI bug: https://bugs.ruby-lang.org/issues/11451.

cc/ @terrellt

**Comment by jperville** [comment]
I didn't know about that bug (and fortunately never experienced).

Regarding the inefficiency of block.call vs yield, note that it is due to the variable binding and not to the block invocation itself (see JuanitoFatas/fast-ruby#68)

**Comment by terrellt** [comment]
Backing out the ones in `repository.rb` fix my tests that were triggering it, and ruby 2.3.0-dev fixes it too. May mean 2.x can use yield and require ruby 2.3?

**Comment by gkellogg** [comment]
We're still compatible with 1.9, and will up to 2.0 for the 2.p release, can't require 2.3 yet. But, withnanduturenupdarenon the 2.2 branch, we can revert back to using yield. In the mean time, if this narrow change fixes your issue, I'll roll it into the develop branch and get a new release staged.

**Pull request closed without merging**
