### PR TITLE
Performance fixes

### PR DESCRIPTION
**Pull request by jperville**
This PR is the sister PR of https://github.com/ruby-rdf/json-ld/pull/41 , where I tried to optimize the object allocation and runtime performance of the `JSON::LD::API#frame method` using [stackprof](https://github.com/tmm1/stackprof).

Each commit should be easy to understand and should not break the `bundle exec rake spec` from this project.

I am interested in your code review @gkellogg before any merge.

### CODE REVIEW

**Comment by gkellogg** [comment]
Good sleuthing! If you have not already done so, please send a [public domain dedication](http://lists.w3.org/Archives/Public/public-rdf-ruby/2010May/0013.html) covering all libraries you may contribute to. Also, consider adding yourself to the CONTRIBUTORS.

**Comment by jperville** [comment]
@gkellogg I just sent the public domain dedication to the public-rdf-ruby mailing-list.

**Comment by gkellogg** [comment]
@jperville didn't show up yet, but I presume it will. Thanks!

**Comment by jperville** [comment]
Hello @gkellogg , could you cut a new release of rdf gem? Thank you very much.

**Comment by gkellogg** [comment]
Released as 2.2.10.

**Pull request merged**
